## ------------------------------------------- Mock ID Integration properties ------------------------------------------------------------
mosip.certify.integration.scan-base-package=io.mosip.certify.mock.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.integration.vci-plugin=MockVCIssuancePlugin

## ------------------------------------------- Mock ID plugin related properties ------------------------------------------------------------
mosip.certify.mock.vciplugin.verification-method=${mosip.certify.authn.jwk-set-uri}
mosip.certify.mock.authenticator.get-identity-url=http://mock-identity-system:8082/v1/mock-identity-system/identity
mosip.certify.cache.security.algorithm-name=AES/ECB/PKCS5Padding
mosip.certify.cache.secure.individual-id=false
mosip.certify.cache.store.individual-id=true
mosip.certify.identifier=http://localhost:8090

mosip.certify.data-provider-plugin.issuer-uri=did:web:som-bee.github.io:DID:sombee
mosip.certify.data-provider-plugin.issuer-public-key-uri=did:web:som-bee.github.io:DID:sombee#key-0

mosip.certify.plugin-mode=DataProvider
mosip.certify.data-provider-plugin.id-field-prefix-uri=https://mosip.io/credential/
mosip.certify.integration.data-provider-plugin=MockCSVDataProviderPlugin
mosip.certify.data-provider-plugin.issuer.vc-sign-algo=Ed25519Signature2020
## CSV specific config
mosip.certify.mock.data-provider.csv.identifier-column=id
#mosip.certify.mock.data-provider.csv.data-columns=id,fullName,mobileNumber,dateOfBirth,gender,state,district,villageOrTown,postalCode,landArea,landOwnershipType,primaryCropType,secondaryCropType,face,farmerID
#mosip.certify.mock.data-provider.csv.data-columns=id,name,phoneNumber,dateOfBirth,certificationLevel,specialization,yearsOfExperience,companyAffiliation,serviceArea,licenseCertificationNumber,dateOfLatestTraining,contactAddress,primarySkills,secondarySkills,professionalQualifications  
#mosip.certify.mock.data-provider.csv-registry-uri=/home/mosip/config/farmer_identity_data.csv
#mosip.certify.mock.data-provider.csv-registry-uri=/home/mosip/config/authorized_service_technicians.csv

# mosip.certify.mock.data-provider.csv.data-columns=id,fullName,dateOfBirth,address,employerName,employerRegId,employerContactName,employerContactNumber,contractStartDate,contractEndDate,photo,employeeID
# mosip.certify.mock.data-provider.csv-registry-uri=/home/mosip/config/employment_data.csv

#mosip.certify.mock.data-provider.csv.data-columns=id,fullName,dateOfBirth,employerName,employerAddress,employerCIN,gstNumber,employerContact,currentlyEmployed,authorizedDevices,photo,technicianID
mosip.certify.mock.data-provider.csv.data-columns=id,institutionName,studentName,degreePursued,graduationYear,certificateTitle,placementSecured,clubName,comments,studentID,photo
#mosip.certify.plugin.csv.file.uri=/home/mosip/config/technician_identity_data.csv
mosip.certify.plugin.csv.file.uri=/home/mosip/config/student_accomplishment_data.csv

mosip.certify.data-provider-plugin.rendering-template-id=
# mosip.certify.key-values={\
#   'latest' : {\
#               'credential_issuer': '${mosip.certify.identifier}',   \
#               'authorization_servers': {'${mosip.certify.authorization.url}'}, \
#               'credential_endpoint': 'https://dfcf-103-51-149-86.ngrok-free.app${server.servlet.path}/issuance/credential', \
#               'display': {{'name': 'Insurance', 'locale': 'en'}},\
#               'credential_configurations_supported' : { \
#                  'FarmerProfileCredential' : {\
#                     'format': 'ldp_vc',\
#                     'scope' : 'mock_identity_vc_ldp',\
#                     'cryptographic_binding_methods_supported': {'did:jwk'},\
#                     'credential_signing_alg_values_supported': {'Ed25519Signature2020'},\
#                     'proof_types_supported': {'jwt': {'proof_signing_alg_values_supported': {'RS256', 'PS256'}}},\
#                     'credential_definition': {\
#                       'type': {'VerifiableCredential','FarmerCredential'},\
#                       'credentialSubject': {\
#                             'fullName': {'display': {{'name': 'Full Name','locale': 'en'}}}, \
#                             'mobileNumber': {'display': {{'name': 'Phone Number','locale': 'en'}}},\
#                             'dateOfBirth': {'display': {{'name': 'Date of Birth','locale': 'en'}}},\
#                             'gender': {'display': {{'name': 'Gender','locale': 'en'}}},\
#                             'state': {'display': {{'name': 'State','locale': 'en'}}},\
#                             'district': {'display': {{'name': 'District','locale': 'en'}}},\
#                             'villageOrTown': {'display': {{'name': 'Village or Town','locale': 'en'}}},\
#                             'postalCode': {'display': {{'name': 'Postal Code','locale': 'en'}}},\
#                             'landArea': {'display': {{'name': 'Land Area','locale': 'en'}}},\
#                             'landOwnershipType': {'display': {{'name': 'Land Ownership Type','locale': 'en'}}},\
#                             'primaryCropType': {'display': {{'name': 'Primary Crop Name','locale': 'en'}}},\
#                             'secondaryCropType': {'display': {{'name': 'Secondary Crop type','locale': 'en'}}},\
#                             'farmerID': {'display': {{'name': 'Farmer ID','locale': 'en'}}}\
#                      }},\
#                     'display': {{'name': 'Farmer Profile Verifiable Credential', \
#                                   'locale': 'en', \
#                                   'logo': {'url': 'https://mosip.github.io/inji-config/logos/agro-vertias-logo.png','alt_text': 'a square logo of a Sunbird'},\
#                                   'background_color': '#FDFAF9',\
#                                   'background_image': { 'uri': 'https://mosip.github.io/inji-config/logos/agro-vertias-logo.png' }, \
#                                   'text_color': '#7C4616'}},\
#                     'order' : {'farmerID','fullName','mobileNumber','dateOfBirth','gender','state','district','villageOrTown','postalCode','landArea','landOwnershipType','primaryCropType','secondaryCropType'}\
#   }}}}

# mosip.certify.key-values={\
#   'latest' : {\
#               'credential_issuer': '${mosip.certify.identifier}',   \
#               'authorization_servers': {'${mosip.certify.authorization.url}'}, \
#               'credential_endpoint': 'https://dfcf-103-51-149-86.ngrok-free.app${server.servlet.path}/issuance/credential', \
#               'display': {{'name': 'Employment Letter', 'locale': 'en'}},\
#               'credential_configurations_supported' : { \
#                  'EmploymentLetterCredential' : {\
#                     'format': 'ldp_vc',\
#                     'scope' : 'mock_identity_vc_ldp',\
#                     'cryptographic_binding_methods_supported': {'did:jwk'},\
#                     'credential_signing_alg_values_supported': {'Ed25519Signature2020'},\
#                     'proof_types_supported': {'jwt': {'proof_signing_alg_values_supported': {'RS256', 'PS256'}}},\
#                     'credential_definition': {\
#                       'type': {'VerifiableCredential','EmploymentCredential'},\
#                       'credentialSubject': {\
#                             'fullName': {'display': {{'name': 'Full Name','locale': 'en'}}}, \
#                             'dateOfBirth': {'display': {{'name': 'Date of Birth','locale': 'en'}}},\
#                             'address': {'display': {{'name': 'Address','locale': 'en'}}},\
#                             'employerName': {'display': {{'name': 'Employer Name','locale': 'en'}}},\
#                             'employerRegId': {'display': {{'name': 'UAE Employer Registered ID','locale': 'en'}}},\
#                             'employerContactName': {'display': {{'name': 'Employer Contact Name','locale': 'en'}}},\
#                             'employerContactNumber': {'display': {{'name': 'Employer Contact Number','locale': 'en'}}},\
#                             'contractStartDate': {'display': {{'name': 'Start Date of Contract','locale': 'en'}}},\
#                             'contractEndDate': {'display': {{'name': 'End Date of Contract','locale': 'en'}}}\
#                      }},\
#                     'display': {{'name': 'Employment Letter Verifiable Credential', \
#                                   'locale': 'en', \
#                                   'logo': {'url': 'https://som-bee.github.io/DID/sombee/images/PngItem_877270.png','alt_text': 'Company Logo'},\
#                                   'background_color': '#FFFFFF',\
#                                   'background_image': { 'uri': 'https://som-bee.github.io/DID/sombee/images/PngItem_877270.png' }, \
#                                   'text_color': '#000000'}},\
#                     'order' : {'fullName','dateOfBirth','address','employerName','employerRegId','employerContactName','employerContactNumber','contractStartDate','contractEndDate'}\
#               }\
#               }}}

#  mosip.certify.key-values={\
#   'latest' : {\
#               'credential_issuer': '${mosip.certify.identifier}',   \
#               'authorization_servers': {'${mosip.certify.authorization.url}'}, \
#               'credential_endpoint': 'https://50c9-103-51-149-86.ngrok-free.app${server.servlet.path}/issuance/credential', \
#               'display': {{'name': 'Service Technician Certificate', 'locale': 'en'}},\
#               'credential_configurations_supported' : { \
#                  'TechnicianProfileCredential' : {\
#                     'format': 'ldp_vc',\
#                     'scope' : 'mock_identity_vc_ldp',\
#                     'cryptographic_binding_methods_supported': {'did:jwk'},\
#                     'credential_signing_alg_values_supported': {'Ed25519Signature2020'},\
#                     'proof_types_supported': {'jwt': {'proof_signing_alg_values_supported': {'RS256', 'PS256'}}},\
#                     'credential_definition': {\
#                       'type': {'VerifiableCredential','TechnicianCredential'},\
#                       'credentialSubject': {\
#                             'fullName': {'display': {{'name': 'Full Name','locale': 'en'}}}, \
#                             'dateOfBirth': {'display': {{'name': 'Date of Birth','locale': 'en'}}},\
#                             'employerName': {'display': {{'name': 'Employer Name','locale': 'en'}}},\
#                             'employerAddress': {'display': {{'name': 'Employer Address','locale': 'en'}}},\
#                             'employerCIN': {'display': {{'name': 'Employer CIN','locale': 'en'}}},\
#                             'gstNumber': {'display': {{'name': 'GST Number','locale': 'en'}}},\
#                             'employerContact': {'display': {{'name': 'Employer Contact','locale': 'en'}}},\
#                             'currentlyEmployed': {'display': {{'name': 'Currently Employed','locale': 'en'}}},\
#                             'authorizedDevices': {'display': {{'name': 'Authorized to Repair','locale': 'en'}}},\
#                             'photo': {'display': {{'name': 'Photo','locale': 'en'}}},\
#                             'technicianID': {'display': {{'name': 'Technician ID','locale': 'en'}}}\
#                      }},\
#                     'display': {{'name': 'Service Technician Verifiable Credential', \
#                                   'locale': 'en', \
#                                   'logo': {'url': 'https://som-bee.github.io/DID/sombee/images/PngItem_877270.png','alt_text': 'Service Technician Logo'},\
#                                   'background_color': '#F5F5F5',\
#                                   'background_image': { 'uri': 'https://som-bee.github.io/DID/sombee/images/PngItem_877270.png' }, \
#                                   'text_color': '#333333'}},\
#                     'order' : {'technicianID','fullName','dateOfBirth','employerName','employerAddress','employerCIN','gstNumber','employerContact','currentlyEmployed','authorizedDevices'}\
#               }\
#               }}}

 mosip.certify.key-values={\
  'latest' : {\
              'credential_issuer': '${mosip.certify.identifier}',   \
              'authorization_servers': {'${mosip.certify.authorization.url}'}, \
              'credential_endpoint': '${mosipbox.public.url}${server.servlet.path}/issuance/credential', \
              'display': {{'name': 'Student Achievement Certificate', 'locale': 'en'}},\
              'credential_configurations_supported' : { \
                 'StudentAccomplishmentCredential' : {\
                    'format': 'ldp_vc',\
                    'scope' : 'mock_identity_vc_ldp',\
                    'cryptographic_binding_methods_supported': {'did:jwk'},\
                    'credential_signing_alg_values_supported': {'Ed25519Signature2020'},\
                    'proof_types_supported': {'jwt': {'proof_signing_alg_values_supported': {'RS256', 'PS256'}}},\
                    'credential_definition': {\
                      'type': {'VerifiableCredential','StudentAccomplishmentCredential'},\
                       'credentialSubject': {\
                            'institutionName': {'display': {{'name': 'Institution Name','locale': 'en'}}}, \
                            'studentName': {'display': {{'name': 'Student Name','locale': 'en'}}},\
                            'degreePursued': {'display': {{'name': 'Degree Program','locale': 'en'}}},\
                            'graduationYear': {'display': {{'name': 'Expected Graduation','locale': 'en'}}},\
                            'certificateTitle': {'display': {{'name': 'Achievement Title','locale': 'en'}}},\
                            'placementSecured': {'display': {{'name': 'Achievement Level','locale': 'en'}}},\
                            'clubName': {'display': {{'name': 'Organization','locale': 'en'}}},\
                            'comments': {'display': {{'name': 'Achievement Details','locale': 'en'}}},\
                            'studentID': {'display': {{'name': 'Student ID','locale': 'en'}}},\
                            'photo': {'display': {{'name': 'Student Photo','locale': 'en'}}}\
                     }},\
                    'display': {{'name': 'Student Achievement Certificate', \
                                  'locale': 'en', \
                                  'logo': {'url': 'https://som-bee.github.io/DID/sombee/images/SUSS_Logo_HorA_FullColor(RGB).jpg','alt_text': 'University Logo'},\
                                  'background_color': '#F5F5F5',\
                                  'background_image': {  'uri': 'https://som-bee.github.io/DID/sombee/images/transparent.png'  }, \
                                  'text_color': '#333333'}},\
                    'order' : {'studentID','studentName','institutionName','degreePursued','graduationYear','certificateTitle','placementSecured','clubName','comments'}\
              }\
              }}}
# mosip.certify.key-values={\
#   'latest' : {\
#               'credential_issuer': '${mosip.certify.identifier}',   \
#               'authorization_servers': {'${mosip.certify.authorization.url}'}, \
#               'credential_endpoint': 'https://50c9-103-51-149-86.ngrok-free.app${server.servlet.path}/issuance/credential', \
#               'display': {{'name': 'Student Achievement Certificate', 'locale': 'en'}},\
#               'credential_configurations_supported' : { \
#                  'StudentAccomplishmentCredential' : {\
#                     'format': 'ldp_vc',\
#                     'scope' : 'mock_identity_vc_ldp',\
#                     'cryptographic_binding_methods_supported': {'did:jwk'},\
#                     'credential_signing_alg_values_supported': {'Ed25519Signature2020'},\
#                     'proof_types_supported': {'jwt': {'proof_signing_alg_values_supported': {'RS256', 'PS256'}}},\
#                     'credential_definition': {\
#                       'type': {'VerifiableCredential','StudentAccomplishmentCredential'},\
#                       'credentialSubject': {\
#                             'institutionName': {'display': {{'name': 'Institution Name','locale': 'en'}}}, \
#                             'studentName': {'display': {{'name': 'Student Name','locale': 'en'}}},\
#                             'degreePursued': {'display': {{'name': 'Degree Program','locale': 'en'}}},\
#                             'graduationYear': {'display': {{'name': 'Expected Graduation','locale': 'en'}}},\
#                             'certificateTitle': {'display': {{'name': 'Achievement Title','locale': 'en'}}},\
#                             'placementSecured': {'display': {{'name': 'Achievement Level','locale': 'en'}}},\
#                             'clubName': {'display': {{'name': 'Organization','locale': 'en'}}},\
#                             'comments': {'display': {{'name': 'Achievement Details','locale': 'en'}}},\
#                             'studentID': {'display': {{'name': 'Student ID','locale': 'en'}}},\
#                             'photo': {'display': {{'name': 'Student Photo','locale': 'en'}}}\
#                      }},\
#                     'display': {{'name': 'Student Achievement Certificate', \
#                                   'locale': 'en', \
#                                   'logo': {'url': 'https://som-bee.github.io/DID/sombee/images/SUSS_Logo_HorA_FullColor(RGB).jpg','alt_text': 'University Logo'},\
#                                   'background_color': '#003D7C',\
#                                   'background_image': { 'uri': '' }, \
#                                   'text_color': '#FFD700'}},\
#                     'order' : {'studentID','studentName','institutionName','degreePursued','graduationYear','certificateTitle','placementSecured','clubName','comments'}\
#               }\
#               }}}